package com.example.springboot.entity;

public class shopping_cart_item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_item.id
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_item.shopping_cart_id
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    private Integer shoppingCartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_item.book_id
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_item.num
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart_item.total
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    private Double total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_item.id
     *
     * @return the value of shopping_cart_item.id
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_item.id
     *
     * @param id the value for shopping_cart_item.id
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_item.shopping_cart_id
     *
     * @return the value of shopping_cart_item.shopping_cart_id
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    public Integer getShoppingCartId() {
        return shoppingCartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_item.shopping_cart_id
     *
     * @param shoppingCartId the value for shopping_cart_item.shopping_cart_id
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    public void setShoppingCartId(Integer shoppingCartId) {
        this.shoppingCartId = shoppingCartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_item.book_id
     *
     * @return the value of shopping_cart_item.book_id
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_item.book_id
     *
     * @param bookId the value for shopping_cart_item.book_id
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_item.num
     *
     * @return the value of shopping_cart_item.num
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_item.num
     *
     * @param num the value for shopping_cart_item.num
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart_item.total
     *
     * @return the value of shopping_cart_item.total
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart_item.total
     *
     * @param total the value for shopping_cart_item.total
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    public void setTotal(Double total) {
        this.total = total;
    }
}