package com.example.springboot.mapper;

import com.example.springboot.entity.book;
import com.example.springboot.entity.bookExample;
import com.example.springboot.entity.bookWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface bookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    long countByExample(bookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int deleteByExample(bookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int insert(bookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int insertSelective(bookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    List<bookWithBLOBs> selectByExampleWithBLOBs(bookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    List<book> selectByExample(bookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    bookWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int updateByExampleSelective(@Param("record") bookWithBLOBs record, @Param("example") bookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") bookWithBLOBs record, @Param("example") bookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int updateByExample(@Param("record") book record, @Param("example") bookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int updateByPrimaryKeySelective(bookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(bookWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int updateByPrimaryKey(book record);
}