package com.example.springboot.mapper;

import com.example.springboot.entity.shopping_cart_item;
import com.example.springboot.entity.shopping_cart_itemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface shopping_cart_itemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart_item
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    long countByExample(shopping_cart_itemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart_item
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int deleteByExample(shopping_cart_itemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart_item
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart_item
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int insert(shopping_cart_item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart_item
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int insertSelective(shopping_cart_item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart_item
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    List<shopping_cart_item> selectByExample(shopping_cart_itemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart_item
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    shopping_cart_item selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart_item
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int updateByExampleSelective(@Param("record") shopping_cart_item record, @Param("example") shopping_cart_itemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart_item
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int updateByExample(@Param("record") shopping_cart_item record, @Param("example") shopping_cart_itemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart_item
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int updateByPrimaryKeySelective(shopping_cart_item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart_item
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    int updateByPrimaryKey(shopping_cart_item record);
}