package com.example.springboot.entity;

public class user {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.privilege
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    private Integer privilege;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.privilege
     *
     * @return the value of user.privilege
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    public Integer getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.privilege
     *
     * @param privilege the value for user.privilege
     *
     * @mbg.generated Wed Dec 01 10:22:29 CST 2021
     */
    public void setPrivilege(Integer privilege) {
        this.privilege = privilege;
    }
}