package com.example.springboot.mapper;

import com.example.springboot.entity.shopping_cart;
import com.example.springboot.entity.shopping_cartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface shopping_cartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    long countByExample(shopping_cartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    int deleteByExample(shopping_cartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    int insert(shopping_cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    int insertSelective(shopping_cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    List<shopping_cart> selectByExample(shopping_cartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    shopping_cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") shopping_cart record, @Param("example") shopping_cartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    int updateByExample(@Param("record") shopping_cart record, @Param("example") shopping_cartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    int updateByPrimaryKeySelective(shopping_cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Nov 25 16:50:38 CST 2021
     */
    int updateByPrimaryKey(shopping_cart record);
}